/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pkgVista;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JSlider;

/**
 *
 * @author user
 */
public class frmVista extends javax.swing.JFrame {
    jplElementos objElementos;
    //llave Q1
    JSlider llaveQ1 = new JSlider();
    //Botones Q2
    JButton Q2Abierto = new JButton();      
     JButton Q2Medio = new JButton();
     JButton Q2Cerrado = new JButton();
     //llama
     JSlider llama = new JSlider();
    /**
     * Creates new form frmVista
     */
    public frmVista() {
        initComponents();
        this.setBounds(20, 20, 900, 600);
        int candela = 50;
        int nivelInicial = 50;
        int temperaturaInicial = 50;
        int caudalQ1 = 10;        
        double diamIniAgujeroQ2 = 0.1;//en metros
        objElementos = new jplElementos(nivelInicial, temperaturaInicial, caudalQ1, diamIniAgujeroQ2, candela);
        
        //llave Q1        
        llaveQ1.setBounds(64, 38, 50, 50);
        llaveQ1.setMaximum(0);
        llaveQ1.setMaximum(10);
        llaveQ1.setValue(10);
        llaveQ1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                llaveQ1StateChanged(evt);
            }
        });
        
        //Botones Q2   
        Q2Abierto.addActionListener(new java.awt.event.ActionListener()
        {   @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                    Q2AbiertoActionPerformed(evt);
                }
        });    
        Q2Abierto.setBounds(330, 270, 80, 30);
        Q2Abierto.setText("Abierto");   
        Q2Abierto.setBackground(Color.white);
       
        Q2Medio.addActionListener(new java.awt.event.ActionListener()
        {   @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                    Q2MedioActionPerformed(evt);
                }
        });
        Q2Medio.setBounds(330, 310, 80, 30);
        Q2Medio.setText("Medio");  
        Q2Medio.setBackground(Color.white);
        
        Q2Cerrado.addActionListener(new java.awt.event.ActionListener()
        {   @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                    Q2CerradoActionPerformed(evt);
                }
        });
        Q2Cerrado.setBounds(330, 350, 80, 30);
        Q2Cerrado.setText("Cerrado");
        Q2Cerrado.setBackground(Color.white);
        
        //llama        
        llama.setBounds(130, 320, 64, 38);
        llama.setMaximum(0);
        llama.setMaximum(100);
        llama.setValue(candela);
        llama.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                llamaStateChanged(evt);
            }
        });
        
        //carga de objetos en panel        
        objElementos.add(llaveQ1);
        objElementos.add(Q2Abierto);
        objElementos.add(Q2Medio);
        objElementos.add(Q2Cerrado);
        objElementos.add(llama);
        
        this.add(objElementos);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   
    private void Q2AbiertoActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        Q2Abierto.setBackground(Color.green);
        Q2Medio.setBackground(Color.white);
        Q2Cerrado.setBackground(Color.white);
        objElementos.caudalSaliente(0.1);
        objElementos.repaint();
        
        
    } 
    private void Q2MedioActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        Q2Medio.setBackground(Color.yellow);
        Q2Abierto.setBackground(Color.white);
        Q2Cerrado.setBackground(Color.white);
        objElementos.caudalSaliente(0.05);
        objElementos.repaint();
      
    }
    private void Q2CerradoActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        Q2Cerrado.setBackground(Color.red);
        Q2Abierto.setBackground(Color.white);
        Q2Medio.setBackground(Color.white);
        objElementos.caudalSaliente(0.00);
        objElementos.repaint();
        
    }
    private void llamaStateChanged(javax.swing.event.ChangeEvent evt) {                                      
        // TODO add your handling code here:
        objElementos.setLlama(llama.getValue());
        objElementos.repaint();
        System.out.println(llama.getValue());
        
    } 
    private void llaveQ1StateChanged(javax.swing.event.ChangeEvent evt) {                                      
        // TODO add your handling code here:
        objElementos.caudalEntrante(llaveQ1.getValue());
        objElementos.repaint();
               
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
